[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200