[build]
  command = "npm install && npm run build"
  publish = "frontend"
  functions = "netlify/functions"
[cache]

  paths = [
    "frontend/node_modules",
    "frontend/package-lock.json",
    "backend/server/package.json",
    "backend\server\node_modules",

  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
